In [1]:
from MLABvo.Bolidozor import Bolidozor
#from MLABvo.Bolidozor import BolidozorTools
import json
import datetime
import numpy as np
import scipy
import scipy.signal
import scipy.constants
from scipy.optimize import minimize
from scipy.interpolate import interp1d, UnivariateSpline
from astropy.io import fits
import matplotlib.pyplot as plt
import matplotlib.dates as md
from matplotlib import dates
from mpl_toolkits.mplot3d.axes3d import Axes3D
import mpltools
import sys
from math import *

sys.path.append("..") 
import recviewer
import dateutil.parser
from Geocentric import Geocentric
geoC = Geocentric(6378137, 6356752.314)

In [18]:
multibolid_id = 2047621


ZHR = 1

if True:#2057410
    multibolid_id = 2057410
    met_start_altitude = np.array([80000.0])
    met_stop_altitude = np.array([44980.37638663])

    met_start_lat = np.array([48.340593635025])
    met_start_lon = np.array([6.572188010297])

    met_stop_lat = np.array([49.52717828089])
    met_stop_lon = np.array([6.763558272451])

    met_velocity = np.array([80000])
    
if False:#2047621
    multibolid_id = 2047621
    met_start_altitude = np.array([80000.0])
    met_stop_altitude = np.array([41896.884619396])

    met_start_lat = np.array([49.997439391249])
    met_start_lon = np.array([9.692504979925])

    met_stop_lat = np.array([50.035327181108])
    met_stop_lon = np.array([7.560013628387])

    met_velocity = np.array([19000])
    
    
if True:#2017388
    multibolid_id = 2017388
    met_start_altitude = np.array([80000.0])
    met_stop_altitude = np.array([8910.7633450924])

    met_stop_lon = np.array([6.512636353428])
    met_stop_lat = np.array([51.944553218498])
    
    met_start_lon = np.array([9.996094184309])
    met_start_lat = np.array([51.230870109095])
    
    met_velocity = np.array([19000])
    
def dist(x,y):   
    return numpy.sqrt(numpy.sum((x-y)**2))

c = scipy.constants.c
f0 = 143050000
graves = np.array(geoC.GeographicToGeocentric(47.347993, 5.515079, 190))
svakov = np.array(geoC.GeographicToGeocentric(49.2607, 14.6917, 400))
valmez = np.array(geoC.GeographicToGeocentric(49.463038, 17.973544, 400))
hfn = np.array(geoC.GeographicToGeocentric(49.1314, 14.9999, 400))

met_pos = [None, None]
met_pos[0] = np.array(geoC.GeographicToGeocentric(45.0, 8, 80000))
met_pos[1] = np.array(geoC.GeographicToGeocentric(44.9, 7.9, 79000))
met_speed = np.array(40000)

print(graves)
print(svakov)
print(valmez)
print(hfn)
print(met_pos)
print(np.linalg.norm(svakov-hfn))

# angle transmitter - meteor - reciever
ba= graves-met_pos[0]
bc= svakov-met_pos[0]
angle1 = np.arccos(np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc)))

# angle trajectory - meteor - reciever
ba= met_pos[1]-met_pos[0]
bc= svakov-met_pos[0]
angle2 = np.arccos(np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc)))

print(angle1, np.degrees(angle1))
print(angle2, np.degrees(angle2))

# angle trajectory - meteor - axis (of angle transmitter-meter-reciever)
angle3 = angle2-angle1/2
print(angle3, np.degrees(angle3))

radial_speed = np.cos(angle3)*met_speed
print(radial_speed)

dd = (1+(radial_speed/c))*f0
print(dd)


[ 4309400.73400393   416092.77960595  4668203.49623901]
[ 4034406.01706163  1057781.97186084  4809833.11880581]
[ 3950989.98813661  1281737.82059318  4824490.01395425]
[ 4039172.39996987  1082285.42683513  4800435.65104368]
[array([ 4529644.01637622,   636599.95096621,  4543916.95110094]), array([ 4537921.04428257,   629688.58050554,  4535247.27493522])]
26673.0221768
1.36027351742 77.9379315313
2.85257631311 163.44058348
2.1724395544 124.471617715
-22639.9169893
143039197.059
